"""
Descriptor utilities for the Swollen Polymer Diffusivity Predictor.
"""

from predictor.predict import SimplePredictorInputs
from predictor.reference import wrapper


def compute_descriptors(inputs: SimplePredictorInputs) -> dict:
    """Return derived descriptors generated by the reference wrapper."""

    return wrapper.build_inputs_from_simple_interface(
        T=inputs.temperature_k,
        Tg_K=inputs.tg_k,
        mass_ratio=inputs.mass_ratio,
        rho_polymer=inputs.rho_polymer,
        rho_solvent=inputs.rho_solvent,
        Polymer_Xc=inputs.polymer_xc,
        CHRIS_Category=inputs.chris_category,
        smiles=inputs.smiles or None,
        cas=inputs.cas or None,
    )