"""Shared constants and utilities for the companion predictor."""

MANUSCRIPT_TITLE = (
    "Predicting Solute Diffusivity in Swollen Polymer Systems "
    "Using Quantile Random Forests and Neural Networks"
)

RESEARCH_USE_DISCLAIMER = """
This provisional companion predictor accompanies the manuscript
"Predicting Solute Diffusivity in Swollen Polymer Systems Using Quantile Random Forests and Neural Networks." [Citation details will be provided when they become available.]

It is provided by the authors to facilitate reproducibility, exploratory analysis, educational use, and application of the machine-learning models reported and used in the manuscript. The predictor is a provisional research implementation and is not an FDA-qualified Regulatory Science Tool (RST), Medical Device Development Tool (MDDT), or FDA-approved decision-support tool. Predictions generated by this predictor should not replace experimental measurements, engineering judgment, or established regulatory evaluation procedures.

The findings and conclusions in the accompanying manuscript are those of the authors and do not necessarily represent any determination or policy of the U.S. Food and Drug Administration. The mention of commercial products, their sources, or their use in connection with material reported therein is not to be construed as either an actual or implied endorsement of such products by the Department of Health and Human Services.

Information regarding FDA-qualified tools is available through the publicly accessible CDRH Regulatory Science Tool (RST) Catalog and Medical Device Development Tool (MDDT) Program.
"""
